filebeat.inputs:
  - type: filestream
    id: {{ component }}
    enabled: true
    paths:
      - {{ log_file }}
    fields:
      component: {{ component }}

output.logstash:
  hosts: ["172.31.4.50:5044"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
processors:
  - drop_fields:
      fields: ["%{HTTPDATE:date}%{SPACE}%{IP:source_ip}%{SPACE}%{WORD:http_method}%{SPACE}%{PATH:http_path}%{SPACE}%{WORD:http_protocol}/%{NUMBER:http_proto_version:float}%{SPACE}%{NUMBER:http_response:int}%{SPACE}%{NUMBER:response_time:float}"]