- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy conf file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Remove Nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: true

#- name: Start Nginx
#  ansible.builtin.systemd:
#    state: restarted
#    name: nginx
#    enabled: true
#
#  func_print_head "Start service"
#  systemctl restart nginx &>>$log_file
#  func_stat_check $?
#  systemctl enable nginx &>>$log_file
#  func_stat_check $?