- name: copy prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

#- name: prometheus port check
#  ansible.builtin.shell: sleep 10 ; netstat -lntp | grep 9090
- name: prometheus port check
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15