- name: copy {{item}} config
  ansible.builtin.template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - alerts

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

#- name: prometheus port check
#  ansible.builtin.shell: sleep 10 ; netstat -lntp | grep 9090
- name: prometheus port check
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15