- name: add application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: true
    filters:
      - name: tag:Monitor
        values: ["true"]