- name: add application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove Nginx content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /usr/share/nginx/html
    remote_src: true