#func_print_head "Install Java"
#dnf install maven -y &>>$log_file
#func_stat_check $?
#
#func_app_prereq
#
#func_print_head "Download dependencies"
#mvn clean package &>>$log_file
#mv target/${component}-1.0.jar ${component}.jar &>>$log_file
#func_stat_check $?
#
#func_systemd_setup
#func_load_schema

- name: Install Java
  ansible.builtin.yum:
    name: maven
    state: installed

- name: app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: download dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Include Systemd
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: Include Schema
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter