#func_app_prereq
#func_print_head "Install dependencies"
#npm install &>>$log_file
#func_stat_check $?
#
#func_systemd_setup
#func_load_schema

- name: Enable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed




