- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt

- name: Include Systemd
  ansible.builtin.import_tasks:
    file: systemd_setup.yml