
#if [ "$load_schema" == "mysql" ]; then
#func_print_head "Load schema"
#dnf install mysql -y &>>${log_file}
#func_stat_check $?
#
#func_print_head "Change mysql default password"
#mysql -h mysql-dev.haseebdevops.online -uroot -p${mysql_root_pass} < /app/schema/shipping.sql &>>${log_file}
#func_stat_check $?


- name: load mongodb schema
  block:
    - name: Setup repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongo client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      ansible.builtin.shell: mongo --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.mongo.endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js
  when: schema_setup == "mongo"


- name: load mysql schema
  block:
    - name: Load schema
      ansible.builtin.yum:
        name: mysql
        state: installed
    - name: Change mysql default password
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.shipping.db_host', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.shipping.db_password', region='us-east-1' ) }} < /app/schema/shipping.sql
  when: schema_setup == "mysql"


