#if [ "$load_schema" == "mongo" ]; then
#func_print_head  "Setup repo file"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#func_stat_check $?
#
#func_print_head "Install Mongo client"
#dnf install mongodb-org-shell -y &>>${log_file}
#func_stat_check $?
#
#func_print_head "load schema"
#mongo --host mongodb-dev.haseebdevops.online </app/schema/catalogue.js &>>${log_file}
#func_stat_check $?
#fi
#if [ "$load_schema" == "mysql" ]; then
#func_print_head "Load schema"
#dnf install mysql -y &>>${log_file}
#func_stat_check $?
#
#func_print_head "Change mysql default password"
#mysql -h mysql-dev.haseebdevops.online -uroot -p${mysql_root_pass} < /app/schema/shipping.sql &>>${log_file}
#func_stat_check $?

- name: Setup repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: schema_setup == "mongo"

- name: Install Mongo client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
  when: schema_setup == "mongo"

- name: load schema
  ansible.builtin.shell: mongo --host {{ lookup('amazon.aws.aws_ssm', 'dev.catalogue.mongo.endpoint', region='us-east-1' ) }} </app/schema/catalogue.js
  when: schema_setup == "mongo"


